### ISSUE TITLE
The plugin's gamedata needs updating

### ISSUE THREAD

**Issue by ManifestManah** [Natanel-Shitrit/MiscChanger#12]
After the most recent CS:GO update a lot of Linux signatures were changed, and as a result the game data files this plugin makes use of need updating. Until the plugin's game data file is updated it will remain broken and unable to work. 
The exception reported in specific is the following:

`L 02/03/2023 - 23:55:56: [SM] Exception reported: Failed to get CCSPlayer::SetRank signature`

**Comment by Natanel-Shitrit** [comment]
Hey @ManifestManah 👋🏼

The `CCSPlayer::SetRank` function got inlined by the compiler in the most recent update.

It won't be possible to find the function signature since the function doesn't exist anymore.

The solution here is to refactor the code so it won't use the `SetRank` function.

I hope that someone who is interested enough will help by doing this since I'm not really active anymore 😔

**Comment by ManifestManah** [comment]
I see. Thank you for replying so quickly to this, especially if you are not active anymore. 
I'd like to say thank you very much for your contribution to the community servers. I know this release of yours have been used, and cherished by a lot of server owners in my country. So I too hope someone will pick up the project, and refactor the code so that people will be able to enjoy its features in the future again :-)

**Comment by Natanel-Shitrit** [comment]
From now on, the plugin is not using `SetRank` function.
I took a quick look into CS:GO source code and saw what player property needed to be changed in order for this to change the coin.

I had a hard time looking at this old and (really) bad code that I wrote.
I've started re-writing it in the past but never finished, the least I can do here is to fix it from being unusable.

I hope you continue to enjoy this plugin.
